//created on: Nov 22, 2020
package com.ilecreurer.drools.samples.sample1

import com.ilecreurer.drools.samples.sample1.Event

declare Event
  @role(event)
  @timestamp (timestamp)
  @expires(value = 20s, policy = TIME_SOFT)
end

rule "Incoming event"
    dialect "mvel"
    when
        e: Event(status == 0) from entry-point "ATM Stream"
    then
        System.out.println("Incoming event: " + e.toString());
        //modify(e) {status = 1};

end

/*
rule "Event with state 1"
    dialect "mvel"
    when
        e: Event(status == 1)
    then
        System.out.println("Removing event: " + e.toString());
        retract(e)
end
*/